name: Bootcamp 2020 urdu
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
         version: 12
    
    - name: GitHub Action for Yarn
    # You may pin to the exact commit or the version.
    # uses: Borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b
      uses: Borales/actions-yarn@v2.1.0
      with:
       # Yarn command
        cmd: install
        
    - name: creating build
      run: npm run build
    
    - name: Installing surge
      run: npm install --global surge
      
    - name: deploy using surge
      run: surge ./build http://fakhruddin-bootcamp.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
